//------------------------------------------------------------------------------
// MiCake Module Template
// Generated by MiCake Agent System
//------------------------------------------------------------------------------
// Template Variables:
// - {{Namespace}}: Root namespace
// - {{ModuleName}}: Name of the module
// - {{Dependencies}}: Module dependencies
// - {{DomainAssembly}}: Assembly containing domain objects
// - {{ServiceRegistrations}}: Custom service registrations
//------------------------------------------------------------------------------

using MiCake;
using MiCake.AspNetCore;
using MiCake.Modularity;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Configuration;

namespace {{Namespace}};

/// <summary>
/// MiCake module for {{ModuleName}}.
/// </summary>
/// <remarks>
/// Module Lifecycle:
/// PreConfigServices → ConfigServices → PostConfigServices 
/// → PreInitialization → Initialization → PostInitialization
/// </remarks>
{{#each Dependencies}}
[RelyOn(typeof({{this}}))]
{{/each}}
public class {{ModuleName}}Module : MiCakeModule
{
    /// <summary>
    /// Pre-configuration phase. Runs before ConfigServices.
    /// Use for early setup that other services might depend on.
    /// </summary>
    public override Task PreConfigServices(ModuleConfigServiceContext context)
    {
        // Early configuration if needed
        return base.PreConfigServices(context);
    }
    
    /// <summary>
    /// Main service configuration phase.
    /// Register your services, repositories, and configure options here.
    /// </summary>
    public override Task ConfigServices(ModuleConfigServiceContext context)
    {
        var services = context.Services;
        var configuration = context.Configuration;
        
        // Auto-register repositories from domain assembly
        context.AutoRegisterRepositories(typeof({{DomainAssemblyMarker}}).Assembly);
        
        {{#each ServiceRegistrations}}
        // {{description}}
        services.{{lifetime}}<{{interface}}, {{implementation}}>();
        
        {{/each}}
        
        // Configure MiCake options
        services.Configure<MiCakeApplicationOptions>(options =>
        {
            options.DomainLayerAssemblies = new[] 
            { 
                typeof({{DomainAssemblyMarker}}).Assembly 
            };
        });
        
        return base.ConfigServices(context);
    }
    
    /// <summary>
    /// Post-configuration phase. Runs after all modules' ConfigServices.
    /// Use for configuration that depends on other modules' registrations.
    /// </summary>
    public override Task PostConfigServices(ModuleConfigServiceContext context)
    {
        return base.PostConfigServices(context);
    }
    
    /// <summary>
    /// Pre-initialization phase. Application is built but not started.
    /// </summary>
    public override Task PreInitialization(ModuleLoadContext context)
    {
        return base.PreInitialization(context);
    }
    
    /// <summary>
    /// Main initialization phase. Configure the application pipeline here.
    /// </summary>
    public override Task Initialization(ModuleLoadContext context)
    {
        var app = context.ServiceProvider;
        
        // Runtime initialization logic
        
        return base.Initialization(context);
    }
    
    /// <summary>
    /// Post-initialization phase. Runs after all modules are initialized.
    /// </summary>
    public override Task PostInitialization(ModuleLoadContext context)
    {
        return base.PostInitialization(context);
    }
    
    /// <summary>
    /// Cleanup phase. Called when the application is shutting down.
    /// </summary>
    public override Task Shutdown(ModuleLoadContext context)
    {
        // Cleanup resources if needed
        return base.Shutdown(context);
    }
}

//------------------------------------------------------------------------------
// EXAMPLES
//------------------------------------------------------------------------------

/*
// Example 1: Simple entry module
[RelyOn(typeof(MiCakeAspNetCoreModule))]
public class MyShopModule : MiCakeModule
{
    public override Task ConfigServices(ModuleConfigServiceContext context)
    {
        context.AutoRegisterRepositories(typeof(MyShop.Domain.AssemblyMarker).Assembly);
        return base.ConfigServices(context);
    }
}

// Example 2: Module with custom services and configuration
[RelyOn(typeof(MiCakeAspNetCoreModule))]
public class OrderModule : MiCakeModule
{
    public override Task ConfigServices(ModuleConfigServiceContext context)
    {
        var services = context.Services;
        var configuration = context.Configuration;
        
        // Auto-register repositories
        context.AutoRegisterRepositories(typeof(Order).Assembly);
        
        // Register application services
        services.AddScoped<IOrderService, OrderService>();
        services.AddScoped<IOrderQueryService, OrderQueryService>();
        
        // Register domain event handlers
        services.AddScoped<IDomainEventHandler<OrderCreatedEvent>, OrderCreatedEventHandler>();
        services.AddScoped<IDomainEventHandler<OrderConfirmedEvent>, OrderConfirmedEventHandler>();
        
        // Configure options from appsettings
        services.Configure<OrderOptions>(configuration.GetSection("Orders"));
        
        // Configure MiCake options
        services.Configure<MiCakeApplicationOptions>(options =>
        {
            options.DomainLayerAssemblies = new[] { typeof(Order).Assembly };
        });
        
        return base.ConfigServices(context);
    }
    
    public override Task Initialization(ModuleLoadContext context)
    {
        var logger = context.ServiceProvider.GetRequiredService<ILogger<OrderModule>>();
        logger.LogInformation("OrderModule initialized");
        
        return base.Initialization(context);
    }
}

// Example 3: Module with dependencies on other custom modules
[RelyOn(typeof(MiCakeAspNetCoreModule))]
[RelyOn(typeof(CommonModule))]      // Depends on CommonModule
[RelyOn(typeof(NotificationModule))] // Depends on NotificationModule
public class CheckoutModule : MiCakeModule
{
    public override Task ConfigServices(ModuleConfigServiceContext context)
    {
        context.AutoRegisterRepositories(typeof(Checkout).Assembly);
        
        context.Services.AddScoped<ICheckoutService, CheckoutService>();
        context.Services.AddScoped<IPaymentProcessor, StripePaymentProcessor>();
        
        return base.ConfigServices(context);
    }
}

// Example 4: Module with background services
[RelyOn(typeof(MiCakeAspNetCoreModule))]
public class ScheduledTaskModule : MiCakeModule
{
    public override Task ConfigServices(ModuleConfigServiceContext context)
    {
        // Register background services
        context.Services.AddHostedService<OrderCleanupService>();
        context.Services.AddHostedService<NotificationQueueProcessor>();
        
        return base.ConfigServices(context);
    }
}
*/

//------------------------------------------------------------------------------
// MODULE DESIGN GUIDELINES
//------------------------------------------------------------------------------
/*
✅ Good practices:
1. One module per bounded context or feature area
2. Explicit dependencies via [RelyOn] attribute
3. Self-contained - module can be removed without breaking others
4. Single responsibility - each module has a clear purpose
5. Use ConfigServices for DI, Initialization for runtime setup

❌ Avoid:
1. Circular module dependencies
2. Accessing other modules' internal services directly
3. Complex logic in module lifecycle methods
4. Tight coupling between modules

Module Dependency Rules:
- Framework modules (MiCakeAspNetCoreModule) should be at the bottom
- Your entry module should be at the top
- Feature modules can depend on shared/common modules
- Domain modules should not depend on infrastructure modules
*/
